exp: TextClassification
# https://github.com/forrestdavis/NLPScholar/blob/main/sample_configs/text_classification.yaml

mode:
  - train

models:
  - hf_text_classification_model:
      - bert-large-uncased
  - hf_text_classification_model:
      - openai-gpt

trainfpath: data/major_CoLA_Annotated.tsv

validfpath: imdb:test

modelfpath: models

loadPretrained: False
