exp: MinimalPair

mode:
  - evaluate

models:
  - hf_text_classification_model:
      - TRAINED_BERT_MODEL_PATH
  - hf_text_classification_model:
      - TRAINED_GPT_MODEL_PATH

datafpath: ./data/major_CoLA_Annotated.tsv
predfpath: ./output/evaluate_result.tsv
# We will take evaluate output and calculate MCC
