exp: TextClassification

mode:
  - train

models:
  # hf_text_classification_model:
  #     - bert-large-uncased
  hf_text_classification_model:
      - gpt2
  

trainfpath: ../data/train_data/train.tsv

validfpath: ../data/train_data/test.tsv

modelfpath: ../models/

batchSize: 64